### ISSUE TITLE
when i add 2 delegate it showing that it doesnt conform to photobrowserdelegate ?.. 

### ISSUE THREAD

**Issue by sreeji44** [tapz/MWPhotoBrowserSwift#7]

**Comment by tapz** [comment]
Does it work with one delegate?

**Comment by sreeji44** [comment]
ya it works when i add the whole delegate function..... can i ask you one thing if you tell it will be very helpful for me... i am using your library i need top bar navigation bar. but bottom for me i need tabbar items which want to transparent. how can i do this.. how can i add tab bar to it.
